apiVersion: v1
kind: ReplicationController
metadata:
  name: nexue
spec:
  replicas: {{ .Values.nexue.replicas }}
  template:
    metadata:
      labels:
        app: nexus
    spec:
      containers:
        - name: nexus
          image: {{ .Values.image.registry }}/nexus3:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8081
