{{- if .Values.configurationFiles }}
apiVersion: apps/v1beta1
kind: ConfigMap
metadata:
  name: {{ template "nexus.fullname" . }}
data:
{{- range $key, $val := .Values.configurationFiles }}
  {{ $key }}: |-
{{ $val | indent 4}}
{{- end }}
{{- end -}}
